### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by cloud-planet** [JaydenForYou/Spring#1]
functions.php的第731行报错，实际浏览主题的文章页的时候可以看到这个错误提示

**Comment by JaydenForYou** [comment]
> functions.php的第731行报错，实际浏览主题的文章页的时候可以看到这个错误提示

**Comment by JaydenForYou** [comment]
> functions.php的第731行报错，实际浏览主题的文章页的时候可以看到这个错误提示

已修复
