### ISSUE TITLE
顶栏和底栏显示有问题

### ISSUE THREAD

**Issue by fxwl** [JaydenForYou/Spring#10]
![image](https://user-images.githubusercontent.com/26475326/79117839-c7595480-7dbe-11ea-81cf-08b5ce348980.png)
![image](https://user-images.githubusercontent.com/26475326/79117852-ce806280-7dbe-11ea-821c-960267ba0770.png)
顶栏和底栏显示有问题

**Comment by fxwl** [comment]
地址ovo.center

**Comment by JaydenForYou** [comment]
> ovo.center

![image](https://user-images.githubusercontent.com/53374430/79124674-6b4afc00-7dcf-11ea-90b1-94ebac64e2f4.png)
正常的，你那边缓存的问题。
