### ISSUE TITLE
使用CDN后自带评论无法评论

### ISSUE THREAD

**Issue by 5Lin** [JaydenForYou/Spring#11]
大佬您好，spring主题使用CDN后，无法评论，小白不知道哪里配置错了还是主题不支持，希望大佬回复下。

![sshot-=](https://user-images.githubusercontent.com/42142628/80045737-f1d3ac00-853a-11ea-989e-515f2ff1569d.png)

**Comment by JaydenForYou** [comment]
> 大佬您好，spring主题使用CDN后，无法评论，小白不知道哪里配置错了还是主题不支持，希望大佬回复下。
> 
> ![sshot-=](https://user-images.githubusercontent.com/42142628/80045737-f1d3ac00-853a-11ea-989e-515f2ff1569d.png)

地址多少，我这边本地无法复现

**Comment by 5Lin** [comment]
> > 大佬您好，spring主题使用CDN后，无法评论，小白不知道哪里配置错了还是主题不支持，希望大佬回复下。
> > 
> > ![sshot-=](https://user-images.githubusercontent.com/42142628/80045737-f1d3ac00-853a-11ea-989e-515f2ff1569d.png)
> 
> 地址多少，我这边本地无法复现


大佬你好  我之后查了一下  是这个原因

https://cloud.tencent.com/developer/article/1525124

按照这个改了下  好了

**Comment by JaydenForYou** [comment]
> > > 大佬您好，spring主题使用CDN后，无法评论，小白不知道哪里配置错了还是主题不支持，希望大佬回复下。
> > > ![sshot-=](https://user-images.githubusercontent.com/42142628/80045737-f1d3ac00-853a-11ea-989e-515f2ff1569d.png)
> > 
> > 
> > 地址多少，我这边本地无法复现
> 
> 大佬你好 我之后查了一下 是这个原因
> 
> https://cloud.tencent.com/developer/article/1525124
> 
> 按照这个改了下 好了

好的
