### ISSUE TITLE
装好后排版看着不对劲

### ISSUE THREAD

**Issue by danpianji** [JaydenForYou/Spring#12]
![图片](https://user-images.githubusercontent.com/25237166/82431484-45e19a00-9ac1-11ea-9b55-ee14b7e2e624.png)
插件全部关闭也还是这样子,应该排除插件影响.

**Comment by JaydenForYou** [comment]
> ![图片](https://user-images.githubusercontent.com/25237166/82431484-45e19a00-9ac1-11ea-9b55-ee14b7e2e624.png)
> 插件全部关闭也还是这样子,应该排除插件影响.

你这明显是CSS样式没加载...F12看资源有没有加载

**Comment by danpianji** [comment]
@JaydenForYou 谢谢,确实是ftp上传的时候css文件夹失败了
