### ISSUE TITLE
移动端bug和一些建议

### ISSUE THREAD

**Issue by longshishui** [JaydenForYou/Spring#14]
主题很好用，很美观且实用。
不过目前使用下来，发现有2个小小的问题～
主要是目录相关的：

1. 能否考虑将多级分类做成悬浮展开的形式，目前是子分类是直接与父级分类并列展示，会出现分类过多的情况。不好看也不好用。
2. 同样是目录过多的情况下，移动端展开侧边的分类导航，向下滑动时，会出现滑了左侧导航不动、右侧内容列表动的情况，希望能解决下。

关于第2点，我的css解决方案如下，希望能作为参考：

```
.site-wrapper .sidebar-wrapper .sidebar-container.boxshadow-right {
    overflow: scroll;
}
```

**Comment by JaydenForYou** [comment]
第一点，没有这个打算，因为这个就想着用自己的风格-.-
第二点，手头上没有demo去复现了，到时候再去看看吧。
