### ISSUE TITLE
移动端头像显示bug

### ISSUE THREAD

**Issue by design-1996** [JaydenForYou/Spring#15]
移动端不显示作者头像。期待作者更新下一个版本。
功能建议：本人小白，不会搞友链，搞了几次把网站直接给搞崩了。希望下个版本增加友链功能，可以直接添加好友网站链接。拜托了作者

**Comment by design-1996** [comment]
呃，启用SSL后，移动端头像显示正常了。 希望作者有空能指导一下如何建友链界面

**Comment by JaydenForYou** [comment]
> 呃，启用SSL后，移动端头像显示正常了。 希望作者有空能指导一下如何建友链界面

后台选模板发布就行了
