### ISSUE TITLE
导航如何添加

### ISSUE THREAD

**Issue by Xunzhuo** [JaydenForYou/Spring#16]

**Comment by Xunzhuo** [comment]
![截屏2020-06-21 00 46 56](https://user-images.githubusercontent.com/48784001/85207050-c1e92f00-b358-11ea-9732-96da25288ccd.png)
搜索栏也出现异常

**Comment by JaydenForYou** [comment]
> ![截屏2020-06-21 00 46 56](https://user-images.githubusercontent.com/48784001/85207050-c1e92f00-b358-11ea-9732-96da25288ccd.png)
> 搜索栏也出现异常

搜索本来就是这样
