### ISSUE TITLE
与Mathjax的兼容问题

### ISSUE THREAD

**Issue by hbc007** [JaydenForYou/Spring#19]
直接引入Mathjax的script标签文章中如果有mathjax的公式，必须得刷新一下才能渲染显示

在网上找到的解决方法是使用`($document).on('pjax:complete')`来加载mathjax的js依赖，我在footer.php引入jq的代码后添加了相应的函数，但是通过调试发现没有执行`'pjax:complete'`的回调

还有cPlayer插件也是需要刷新页面才能渲染，应该也是同种类型的的问题

请问我需要在哪个地方进行修改才能解决这个问题？

**Comment by JaydenForYou** [comment]
在我博客上有一篇文章讲到typecho的pjax 可以去看看
