### ISSUE TITLE
备案域名问题

### ISSUE THREAD

**Issue by YSevenK** [JaydenForYou/Spring#24]
作者大佬你好，备案号问题可能官方备案域名修改了，填入备案号后无法正确跳转到备案系统，我本地已经改好没有问题，已提交PR

**Comment by unsafe-ptr** [comment]
> 作者大佬你好，备案号问题可能官方备案域名修改了，填入备案号后无法正确跳转到备案系统，我本地已经改好没有问题，已提交PR

已合，辛苦。
