### ISSUE TITLE
search页面，option->logoUrl，NickName，bio无法获取到值

### ISSUE THREAD

**Issue by liqilinhub** [JaydenForYou/Spring#3]
search页面，option->logoUrl，NickName，bio无法获取到值，导致页面无法正确显示，设置的github链接正常。并且未查询到结果时，提示关键字后面会带index.php。

**Comment by JaydenForYou** [comment]
> search页面，option->logoUrl，NickName，bio无法获取到值，导致页面无法正确显示，设置的github链接正常。并且未查询到结果时，提示关键字后面会带index.php。

主题重构了一部分，建议下载最新的文件吧。
