### ISSUE TITLE
Valine评论提示非法请求

### ISSUE THREAD

**Issue by NoverNobida** [JaydenForYou/Spring#6]
填入Valine appid, appkey, 安全域名及开启评论之后，评论显示“非法请求”。另外，能否关闭必须填入网址？

**Comment by JaydenForYou** [comment]
> 填入Valine appid, appkey, 安全域名及开启评论之后，评论显示“非法请求”。另外，能否关闭必须填入网址？

安全域名可不填

**Comment by JaydenForYou** [comment]
还有任何问题，请邮箱联系i#iobiji.com
