### ISSUE TITLE
底部标签栏错误？内容也有点问题？

### ISSUE THREAD

**Issue by BooYeu** [JaydenForYou/Spring#8]

**Comment by BooYeu** [comment]
显示静态：前端
后端
Java
JavaScript
Golang
Python
生活
吃货
标签
年假
假期
电脑
键盘
鼠标
显卡
CPU
内存条
主板
微信

**Comment by JaydenForYou** [comment]
> 显示静态：前端
> 后端
> Java
> JavaScript
> Golang
> Python
> 生活
> 吃货
> 标签
> 年假
> 假期
> 电脑
> 键盘
> 鼠标
> 显卡
> CPU
> 内存条
> 主板
> 微信

目前只是demo，没做功能

**Comment by JaydenForYou** [comment]
> > 显示静态：前端
> > 后端
> > Java
> > JavaScript
> > Golang
> > Python
> > 生活
> > 吃货
> > 标签
> > 年假
> > 假期
> > 电脑
> > 键盘
> > 鼠标
> > 显卡
> > CPU
> > 内存条
> > 主板
> > 微信
> 
> 目前只是demo，没做功能

已更新。
