### ISSUE TITLE
在分类下文章分页按钮链接地址错误

### ISSUE THREAD

**Issue by liqilinhub** [JaydenForYou/Spring#9]
主页底部分页按钮链接正确，但在某个分类下分页按钮链接地址错误。
[参考链接](http://liqilinhub.cloud/category/code/)，点击下一页。

**Comment by JaydenForYou** [comment]
> 主页底部分页按钮链接正确，但在某个分页下按钮链接地址错误。
> [参考链接](http://liqilinhub.cloud/category/code/)，点击下一页。

使用非PJAX版本吧，pjax版本不进行更新维护了

**Comment by liqilinhub** [comment]
谢谢，已经解决，经过正则修饰之后，首页和分类下都正常，将上一页和下一页href 分别改为
`<?=$site.(preg_filter('/index.php/','',$page)).$prev?>`  和 
`<?=$site.(preg_filter('/index.php/','',$page)).$next?>`  即可。

**Comment by liqilinhub** [comment]
> > 主页底部分页按钮链接正确，但在某个分页下按钮链接地址错误。
> > [参考链接](http://liqilinhub.cloud/category/code/)，点击下一页。
> 
> 使用非PJAX版本吧，pjax版本不进行更新维护了

谢谢，已经解决，经过正则修饰之后，首页和分类下都正常，将上一页和下一页href 分别改为
`<?=$site.(preg_filter('/index.php/','',$page)).$prev?>`  和 
`<?=$site.(preg_filter('/index.php/','',$page)).$next?>`  即可。

**Comment by JaydenForYou** [comment]
> <?=$site.(preg_filter('/index.php/','',$page)).$prev?>

OK，谢谢
